#!/bin/bash
# author: 	ortizimo
# date: 	2025.10.18
# update: 	2026.05.29
# version: 	1.3

clear
echo ""
echo "************************"
echo -e "\033[1;33m 	backupNOW! \033[0m"
echo -e "\033[1;33m 	   v1.3 \033[0m"
echo "************************"
echo ""
echo "RUN THIS SCRIPT FROM ROOT OF HOME!"
while true; do
	read -p "Did you backup to an external HDD (n) or do you want to continue (y) " ny
	case $ny in
		[Nn]* ) 
			echo -e "\033[1;33mExiting now!\033[0m"
			exit 1; break;;
		[Yy]* )
			echo ""
			echo -e "\033[1;33mDeleting previous backup version...\033[0m"
			echo "-----------------------------------"
			sleep 1
			sudo rm -rf backup/; break;;
	esac
done
echo -e "\033[1;33mDeletion completed!\033[0m"
sleep 2

clear

echo -e "\033[1;33mCopying ROMS and scraped art to backup dir now...\033[0m"
echo "------------------------------------------"
sleep 2
sudo cp -Rv retrodeck/ backup/ --force
echo -e "\033[1;33mAll retrodeck files copied!\033[0m"
sleep 2

clear

echo -e "\033[1;33mCopying all the BASH scripts now...\033[0m"
echo "-SHUTDOWN SCRIPT-----------------------"
sudo cp /usr/local/bin/shutdown.sh backup/
sleep 1
echo "--SHUTDOWN SERVICE SCRIPT--------------"
sudo cp ~/.config/systemd/user/shutdown.service backup/
sleep 1
echo "---BACKUPNOW SCRIPT--------------------"
sudo cp /usr/local/bin/backupNOW backup/
echo -e "\033[1;33mCopying complete!\033[0m"
sleep 2

clear

echo -e "\033[1;33mCopying the hidden .VAR DIR now...\033[0m"
sudo mkdir -p backup/var/app
sudo cp -Rv .var/app/net.retrodeck.retrodeck/ backup/var/app/
echo -e "\033[1;33mCopying complete!\033[0m"
echo "This hidden data goes in the main HOME DIR when restored!"
sleep 5

clear

echo -e "\033[1;33mMaking sure all files permissions are set for the CURRENT user\033[0m"
echo "--------------------------------------------------------------"
sleep 2
sudo chown -R bazzite:bazzite backup/	#change this to your own user:system
echo -e "\033[1;33mAll files copied successfully!\033[0m"
ls -l backup/
echo -e "\033[1;33mTotal file space used in DEST dir: \033[0m $(du -sh backup/)"
sleep 2
echo -e "\033[1;33mTotal files copied from SRC dir: \033[0m $(du -sh retrodeck/)"
sleep 2
echo -e "\033[1;33mTotal DRV space: \033[0m \n$(df -h | grep -i 'var/home\|avail')"
echo ""
echo -e "\033[1;33mEVERYTHING IS NOW COPIED! Don't forget to backup to an external drive soon!\033[0m" 
echo -e "\nNotes:"
echo "1. Controller and scanlines configuration are NOT backed up!"
echo "2. All backed up scripts go in /usr/local/bin dir"
echo "3. Remember that the .var/app/net.retrodeck.retrodeck DIR goes in the HOME DIR and must be hidden to work!"
sleep 2
echo ""
